### ISSUE TITLE
It works only on localhost

### ISSUE THREAD

**Issue by ruafelianna** [exane/not-gwent-online#5]
Hello! I did everything you've written in readme file. And the game works on localhost (I even can play with myself :D). But it doesn't work on my local network (e.g. when I set the address to 192.168.123.1). I tried to make something with virtual hosts in wamp (and something worked but server status was offline). So what must I do to play with my friends?
P.S. The game is awesome, you are great! :)

**Comment by exane** [comment]
It seems your node server cannot connect with your client. I would guess the problem lies within you vhost config.

You could try to set up xampp, which is easier to handle if you aren't familar with this stuff, since it comes with a default config that should work out of the box without using vhosts. Other than that, I'm afraid, I'm not much of a help and you should read about how to config a webserver.

But thanks for your feedback and I appreciate your interest  :) 
good luck
